//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string Subj { get; set; }
        public Nullable<int> Note1 { get; set; }
        public int StudentId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
